### PR TITLE
Redirect from docs to documentation (follow-up)

### PR DESCRIPTION
**Pull request by jcfr**
Follow-up of https://github.com/slicersalt/slicersalt.github.io/pull/8

### CODE REVIEW

**Review by bpaniagua — COMMENTED** [review]
good.

**Review by bpaniagua — COMMENTED** [review]
good

**Comment by jcfr** [comment]
Redirect is now confirmed to work :+1: 

image

**Comment by bpaniagua** [comment]
thank you, @jcfr!

**Comment by jcfr** [comment]
I confirmed that this follow up PR fixes https://github.com/Kitware/SlicerSALT/issues/288

**Pull request merged**
